-- 058: Seed công thức Tiệm Cúc Quý — NVL + 4 bán thành phẩm + 21 món (bánh/cookie/nước).
-- Đơn giá NVL = giá max đã chốt; công/vận hành/bao bì/hao hụt/margin theo bảng đã duyệt.
-- Idempotent: ON CONFLICT(name) DO NOTHING cho NVL/công thức; dòng chỉ chèn nếu recipe chưa có dòng.

-- 1) NGUYÊN LIỆU ------------------------------------------------------------
INSERT INTO cost_ingredients (name, unit, unit_price) VALUES
  ('Đường trắng','g',19), ('Đường nâu','g',30), ('Bột bắp','g',40), ('Matcha','g',760),
  ('Sữa tươi','ml',28), ('Whipping','ml',220), ('Bột mì số 13','g',28), ('Bột mì số 8','g',14),
  ('Bột mì đa dụng','g',15), ('Muối','g',5), ('Men','g',200), ('Bột cacao','g',190),
  ('Socola đen 65%','g',370), ('Socola tảng','g',250), ('Sữa đặc','ml',80), ('Cream cheese','g',200),
  ('Nescafe 3in1 đỏ','goi',3500), ('Bột cà phê','g',350), ('Rum','ml',250), ('Vanilla','ml',500),
  ('Giấm','ml',57), ('Phẩm màu đỏ','ml',200), ('Baking powder','g',120), ('Baking soda','g',120),
  ('Bơ lạt','g',100), ('Bơ Thái','g',80), ('Dầu ăn','ml',56), ('Trứng','qua',3500),
  ('Lòng đỏ trứng','qua',2500), ('Chuối','g',14), ('Táo','g',25), ('Bột quế','g',200),
  ('Tắc','qua',800), ('Bột năng','g',20), ('Đế tart','cai',2600), ('Hạt sen','g',190),
  ('Chôm chôm','qua',1923), ('Cam ép','ml',60), ('Trà khô lài','g',220), ('Trà cozy pha','ml',10),
  ('Syrup đào','ml',193), ('Mứt đào','g',94), ('Syrup vải','ml',150), ('Đào lát','g',37),
  ('Cà phê','g',350), ('Bột sữa','g',50), ('Nước lọc','ml',0)
ON CONFLICT (name) DO NOTHING;

-- 2) BÁN THÀNH PHẨM ---------------------------------------------------------
INSERT INTO cost_recipes (name, kind, category, yield_qty, yield_unit) VALUES
  ('Trà lài (BTP)','semi',NULL,1500,'ml'),
  ('Syrup đường (BTP)','semi',NULL,1100,'ml'),
  ('Cà phê pha (BTP)','semi',NULL,70,'ml'),
  ('Kem cheese (BTP)','semi',NULL,400,'ml')
ON CONFLICT (name) DO NOTHING;

-- 3) SẢN PHẨM BÁN -----------------------------------------------------------
INSERT INTO cost_recipes
  (name, kind, category, yield_qty, yield_unit, labor_tier, labor_cost, overhead_cost, packaging_cost, waste_pct, margin_pct)
VALUES
  -- Bánh
  ('Donut matcha custard','product','cake',24,'cai','hard',2500,1500,1000,0.05,0.4),
  ('Canelé','product','cake',24,'cai','hard',2500,1500,1000,0.05,0.5),
  ('Apple pie nhỏ','product','cake',10,'cai','medium',1500,1500,1000,0.05,0.4),
  ('Brownie','product','cake',9,'mieng','medium',744,278,500,0.05,0.4),
  ('Bánh mì dưa lưới','product','cake',6,'cai','medium',1500,1500,1000,0.05,0.4),
  ('Tart trứng cheese','product','cake',14,'cai','easy',800,1500,1000,0.05,0.4),
  ('Phô mai dẻo','product','cake',36,'cai','easy',800,250,170,0.05,0.5),
  ('Banana bread','product','cake',10,'lat','easy',900,250,500,0.05,0.3),
  -- Cookie
  ('Chocolate cookie','product','cookie',21,'cai','easy',800,1000,1000,0.05,0.5),
  ('Matcha cream cookie','product','cookie',21,'cai','easy',800,1000,1000,0.05,0.4),
  ('Red velvet cream cookie','product','cookie',21,'cai','easy',800,1000,1000,0.05,0.4),
  ('Coffee cream cookie','product','cookie',21,'cai','easy',800,1000,1000,0.05,0.4),
  -- Nước
  ('Trà đào','product','drink',1,'ly','easy',800,500,1800,0.05,0.3),
  ('Trà chôm chôm','product','drink',1,'ly','medium',1500,500,1800,0.05,0.2),
  ('Trà sen','product','drink',1,'ly','easy',800,500,1800,0.05,0.5),
  ('Cafe đen','product','drink',1,'ly','easy',800,500,1800,0.05,0.3),
  ('Cafe sữa','product','drink',1,'ly','easy',800,500,1800,0.05,0.4),
  ('Cà phê muối','product','drink',1,'ly','easy',800,500,1800,0.05,0.5),
  ('Sữa nóng','product','drink',1,'ly','easy',800,500,1800,0.05,0.3),
  ('Ca cao đá','product','drink',1,'ly','easy',800,500,1800,0.05,0.4),
  ('Ép cam','product','drink',1,'ly','easy',800,500,1800,0.05,0.3)
ON CONFLICT (name) DO NOTHING;

-- 4) DÒNG CÔNG THỨC ---------------------------------------------------------
-- v(rname, iname, cname, qty, unit, sort): iname=NVL | cname=bán thành phẩm (đa tầng)
INSERT INTO cost_recipe_lines (recipe_id, ingredient_id, child_recipe_id, qty, unit, sort_order)
SELECT r.id, ci.id, cr.id, v.qty, v.unit, v.sort
FROM (VALUES
  -- Bán thành phẩm
  ('Trà lài (BTP)','Trà khô lài',NULL,50,'g',1),
  ('Trà lài (BTP)','Nước lọc',NULL,1500,'ml',2),
  ('Syrup đường (BTP)','Đường trắng',NULL,1000,'g',1),
  ('Syrup đường (BTP)','Nước lọc',NULL,600,'ml',2),
  ('Cà phê pha (BTP)','Cà phê',NULL,25,'g',1),
  ('Cà phê pha (BTP)','Nước lọc',NULL,95,'ml',2),
  ('Kem cheese (BTP)','Whipping',NULL,75,'ml',1),
  ('Kem cheese (BTP)','Sữa tươi',NULL,125,'ml',2),
  ('Kem cheese (BTP)','Sữa đặc',NULL,30,'ml',3),
  ('Kem cheese (BTP)','Muối',NULL,4,'g',4),
  ('Kem cheese (BTP)','Bột sữa',NULL,10,'g',5),
  -- Nước
  ('Trà đào',NULL,'Trà lài (BTP)',150,'ml',1),
  ('Trà đào','Trà cozy pha',NULL,75,'ml',2),
  ('Trà đào','Syrup đào',NULL,10,'ml',3),
  ('Trà đào','Mứt đào',NULL,20,'g',4),
  ('Trà đào',NULL,'Syrup đường (BTP)',20,'ml',5),
  ('Trà đào','Tắc',NULL,1,'qua',6),
  ('Trà đào','Đào lát',NULL,30,'g',7),
  ('Trà chôm chôm','Đường trắng',NULL,10,'g',1),
  ('Trà chôm chôm',NULL,'Syrup đường (BTP)',10,'ml',2),
  ('Trà chôm chôm',NULL,'Trà lài (BTP)',120,'ml',3),
  ('Trà chôm chôm','Nước lọc',NULL,50,'ml',4),
  ('Trà chôm chôm','Syrup vải',NULL,20,'ml',5),
  ('Trà chôm chôm','Tắc',NULL,1,'qua',6),
  ('Trà chôm chôm','Chôm chôm',NULL,6,'qua',7),
  ('Trà sen',NULL,'Trà lài (BTP)',150,'ml',1),
  ('Trà sen',NULL,'Syrup đường (BTP)',40,'ml',2),
  ('Trà sen','Nước lọc',NULL,50,'ml',3),
  ('Trà sen','Hạt sen',NULL,30,'g',4),
  ('Trà sen',NULL,'Kem cheese (BTP)',30,'ml',5),
  ('Cafe đen',NULL,'Cà phê pha (BTP)',50,'ml',1),
  ('Cafe đen','Đường trắng',NULL,8,'g',2),
  ('Cafe sữa',NULL,'Cà phê pha (BTP)',50,'ml',1),
  ('Cafe sữa','Sữa đặc',NULL,20,'ml',2),
  ('Cà phê muối',NULL,'Cà phê pha (BTP)',50,'ml',1),
  ('Cà phê muối','Sữa đặc',NULL,10,'ml',2),
  ('Cà phê muối',NULL,'Kem cheese (BTP)',30,'ml',3),
  ('Sữa nóng','Sữa đặc',NULL,30,'ml',1),
  ('Sữa nóng','Sữa tươi',NULL,20,'ml',2),
  ('Sữa nóng','Whipping',NULL,10,'ml',3),
  ('Sữa nóng','Nước lọc',NULL,120,'ml',4),
  ('Ca cao đá','Bột cacao',NULL,8,'g',1),
  ('Ca cao đá','Nước lọc',NULL,75,'ml',2),
  ('Ca cao đá','Sữa tươi',NULL,100,'ml',3),
  ('Ca cao đá','Sữa đặc',NULL,35,'ml',4),
  ('Ép cam','Cam ép',NULL,100,'ml',1),
  ('Ép cam','Nước lọc',NULL,50,'ml',2),
  ('Ép cam','Tắc',NULL,1,'qua',3),
  -- Donut
  ('Donut matcha custard','Lòng đỏ trứng',NULL,12,'qua',1),
  ('Donut matcha custard','Đường trắng',NULL,180,'g',2),
  ('Donut matcha custard','Bột bắp',NULL,80,'g',3),
  ('Donut matcha custard','Matcha',NULL,40,'g',4),
  ('Donut matcha custard','Sữa tươi',NULL,1080,'ml',5),
  ('Donut matcha custard','Whipping',NULL,240,'ml',6),
  ('Donut matcha custard','Bột mì số 13',NULL,700,'g',7),
  ('Donut matcha custard','Bột mì số 8',NULL,300,'g',8),
  ('Donut matcha custard','Đường trắng',NULL,140,'g',9),
  ('Donut matcha custard','Muối',NULL,12,'g',10),
  ('Donut matcha custard','Men',NULL,12,'g',11),
  ('Donut matcha custard','Trứng',NULL,4,'qua',12),
  ('Donut matcha custard','Sữa tươi',NULL,340,'ml',13),
  ('Donut matcha custard','Bơ lạt',NULL,120,'g',14),
  -- Canelé
  ('Canelé','Sữa tươi',NULL,500,'ml',1),
  ('Canelé','Bơ lạt',NULL,40,'g',2),
  ('Canelé','Trứng',NULL,1,'qua',3),
  ('Canelé','Lòng đỏ trứng',NULL,2,'qua',4),
  ('Canelé','Muối',NULL,2,'g',5),
  ('Canelé','Đường trắng',NULL,145,'g',6),
  ('Canelé','Bột mì đa dụng',NULL,130,'g',7),
  ('Canelé','Vanilla',NULL,8,'ml',8),
  ('Canelé','Rum',NULL,30,'ml',9),
  -- Apple pie
  ('Apple pie nhỏ','Bột mì đa dụng',NULL,340,'g',1),
  ('Apple pie nhỏ','Bơ lạt',NULL,230,'g',2),
  ('Apple pie nhỏ','Đường trắng',NULL,16,'g',3),
  ('Apple pie nhỏ','Muối',NULL,2,'g',4),
  ('Apple pie nhỏ','Nước lọc',NULL,70,'ml',5),
  ('Apple pie nhỏ','Táo',NULL,600,'g',6),
  ('Apple pie nhỏ','Bột quế',NULL,3,'g',7),
  ('Apple pie nhỏ','Đường nâu',NULL,40,'g',8),
  ('Apple pie nhỏ','Bột bắp',NULL,5,'g',9),
  ('Apple pie nhỏ','Tắc',NULL,1.5,'qua',10),
  ('Apple pie nhỏ','Lòng đỏ trứng',NULL,1,'qua',11),
  ('Apple pie nhỏ','Sữa tươi',NULL,10,'ml',12),
  -- Brownie
  ('Brownie','Trứng',NULL,2,'qua',1),
  ('Brownie','Đường nâu',NULL,70,'g',2),
  ('Brownie','Đường trắng',NULL,70,'g',3),
  ('Brownie','Bơ lạt',NULL,100,'g',4),
  ('Brownie','Socola đen 65%',NULL,35,'g',5),
  ('Brownie','Muối',NULL,3,'g',6),
  ('Brownie','Vanilla',NULL,7,'ml',7),
  ('Brownie','Bột cacao',NULL,60,'g',8),
  ('Brownie','Bột mì đa dụng',NULL,45,'g',9),
  -- Bánh mì dưa lưới
  ('Bánh mì dưa lưới','Bột mì số 13',NULL,250,'g',1),
  ('Bánh mì dưa lưới','Đường trắng',NULL,55,'g',2),
  ('Bánh mì dưa lưới','Men',NULL,3,'g',3),
  ('Bánh mì dưa lưới','Muối',NULL,2,'g',4),
  ('Bánh mì dưa lưới','Sữa tươi',NULL,110,'ml',5),
  ('Bánh mì dưa lưới','Bơ lạt',NULL,65,'g',6),
  ('Bánh mì dưa lưới','Trứng',NULL,2,'qua',7),
  ('Bánh mì dưa lưới','Vanilla',NULL,3,'ml',8),
  ('Bánh mì dưa lưới','Bột mì số 8',NULL,110,'g',9),
  ('Bánh mì dưa lưới','Matcha',NULL,5,'g',10),
  ('Bánh mì dưa lưới','Baking powder',NULL,2,'g',11),
  -- Tart
  ('Tart trứng cheese','Whipping',NULL,150,'ml',1),
  ('Tart trứng cheese','Sữa tươi',NULL,100,'ml',2),
  ('Tart trứng cheese','Đường trắng',NULL,45,'g',3),
  ('Tart trứng cheese','Lòng đỏ trứng',NULL,4,'qua',4),
  ('Tart trứng cheese','Bột bắp',NULL,20,'g',5),
  ('Tart trứng cheese','Cream cheese',NULL,28,'g',6),
  ('Tart trứng cheese','Đế tart',NULL,14,'cai',7),
  -- Phô mai dẻo
  ('Phô mai dẻo','Cream cheese',NULL,100,'g',1),
  ('Phô mai dẻo','Bột năng',NULL,135,'g',2),
  ('Phô mai dẻo','Bột bắp',NULL,20,'g',3),
  ('Phô mai dẻo','Dầu ăn',NULL,55,'ml',4),
  ('Phô mai dẻo','Sữa tươi',NULL,170,'ml',5),
  ('Phô mai dẻo','Trứng',NULL,1,'qua',6),
  ('Phô mai dẻo','Đường trắng',NULL,25,'g',7),
  ('Phô mai dẻo','Muối',NULL,2,'g',8),
  -- Banana bread
  ('Banana bread','Chuối',NULL,360,'g',1),
  ('Banana bread','Đường trắng',NULL,60,'g',2),
  ('Banana bread','Đường nâu',NULL,93,'g',3),
  ('Banana bread','Dầu ăn',NULL,90,'ml',4),
  ('Banana bread','Trứng',NULL,3,'qua',5),
  ('Banana bread','Sữa tươi',NULL,180,'ml',6),
  ('Banana bread','Bột cà phê',NULL,8,'g',7),
  ('Banana bread','Rum',NULL,15,'ml',8),
  ('Banana bread','Bột cacao',NULL,18,'g',9),
  ('Banana bread','Socola tảng',NULL,30,'g',10),
  ('Banana bread','Socola đen 65%',NULL,20,'g',11),
  ('Banana bread','Bột mì đa dụng',NULL,270,'g',12),
  ('Banana bread','Bột bắp',NULL,30,'g',13),
  ('Banana bread','Baking powder',NULL,5,'g',14),
  ('Banana bread','Baking soda',NULL,3,'g',15),
  ('Banana bread','Muối',NULL,3,'g',16),
  -- Chocolate cookie
  ('Chocolate cookie','Bơ Thái',NULL,190,'g',1),
  ('Chocolate cookie','Đường nâu',NULL,60,'g',2),
  ('Chocolate cookie','Đường trắng',NULL,47,'g',3),
  ('Chocolate cookie','Trứng',NULL,2,'qua',4),
  ('Chocolate cookie','Bột mì đa dụng',NULL,340,'g',5),
  ('Chocolate cookie','Baking soda',NULL,1.5,'g',6),
  ('Chocolate cookie','Baking powder',NULL,1.5,'g',7),
  ('Chocolate cookie','Bột cacao',NULL,20,'g',8),
  ('Chocolate cookie','Bột cacao',NULL,15,'g',9),
  ('Chocolate cookie','Socola đen 65%',NULL,20,'g',10),
  ('Chocolate cookie','Sữa đặc',NULL,40,'ml',11),
  ('Chocolate cookie','Bơ lạt',NULL,20,'g',12),
  ('Chocolate cookie','Sữa tươi',NULL,5,'ml',13),
  -- Matcha cream cookie
  ('Matcha cream cookie','Bơ Thái',NULL,190,'g',1),
  ('Matcha cream cookie','Đường nâu',NULL,60,'g',2),
  ('Matcha cream cookie','Đường trắng',NULL,47,'g',3),
  ('Matcha cream cookie','Trứng',NULL,2,'qua',4),
  ('Matcha cream cookie','Bột mì đa dụng',NULL,340,'g',5),
  ('Matcha cream cookie','Baking soda',NULL,1.5,'g',6),
  ('Matcha cream cookie','Baking powder',NULL,1.5,'g',7),
  ('Matcha cream cookie','Matcha',NULL,20,'g',8),
  ('Matcha cream cookie','Cream cheese',NULL,200,'g',9),
  ('Matcha cream cookie','Sữa đặc',NULL,20,'ml',10),
  ('Matcha cream cookie','Đường trắng',NULL,10,'g',11),
  ('Matcha cream cookie','Sữa tươi',NULL,5,'ml',12),
  -- Red velvet cream cookie
  ('Red velvet cream cookie','Bơ Thái',NULL,190,'g',1),
  ('Red velvet cream cookie','Đường nâu',NULL,60,'g',2),
  ('Red velvet cream cookie','Đường trắng',NULL,47,'g',3),
  ('Red velvet cream cookie','Trứng',NULL,2,'qua',4),
  ('Red velvet cream cookie','Bột mì đa dụng',NULL,340,'g',5),
  ('Red velvet cream cookie','Baking soda',NULL,1.5,'g',6),
  ('Red velvet cream cookie','Baking powder',NULL,1.5,'g',7),
  ('Red velvet cream cookie','Bột cacao',NULL,8,'g',8),
  ('Red velvet cream cookie','Giấm',NULL,2,'ml',9),
  ('Red velvet cream cookie','Phẩm màu đỏ',NULL,10,'ml',10),
  ('Red velvet cream cookie','Vanilla',NULL,2,'ml',11),
  ('Red velvet cream cookie','Muối',NULL,1,'g',12),
  ('Red velvet cream cookie','Cream cheese',NULL,200,'g',13),
  ('Red velvet cream cookie','Sữa đặc',NULL,20,'ml',14),
  ('Red velvet cream cookie','Đường trắng',NULL,10,'g',15),
  ('Red velvet cream cookie','Sữa tươi',NULL,5,'ml',16),
  -- Coffee cream cookie
  ('Coffee cream cookie','Bơ Thái',NULL,190,'g',1),
  ('Coffee cream cookie','Đường nâu',NULL,60,'g',2),
  ('Coffee cream cookie','Đường trắng',NULL,47,'g',3),
  ('Coffee cream cookie','Trứng',NULL,2,'qua',4),
  ('Coffee cream cookie','Bột mì đa dụng',NULL,340,'g',5),
  ('Coffee cream cookie','Baking soda',NULL,1.5,'g',6),
  ('Coffee cream cookie','Baking powder',NULL,1.5,'g',7),
  ('Coffee cream cookie','Bột cacao',NULL,10,'g',8),
  ('Coffee cream cookie','Nescafe 3in1 đỏ',NULL,2,'goi',9),
  ('Coffee cream cookie','Cream cheese',NULL,200,'g',10),
  ('Coffee cream cookie','Sữa đặc',NULL,20,'ml',11),
  ('Coffee cream cookie','Đường trắng',NULL,10,'g',12),
  ('Coffee cream cookie','Sữa tươi',NULL,5,'ml',13)
) AS v(rname, iname, cname, qty, unit, sort)
JOIN cost_recipes r        ON r.name = v.rname
LEFT JOIN cost_ingredients ci ON ci.name = v.iname
LEFT JOIN cost_recipes cr  ON cr.name = v.cname
WHERE NOT EXISTS (SELECT 1 FROM cost_recipe_lines l2 WHERE l2.recipe_id = r.id);
